package org.uj.routingemulator.common.forwarding;

public enum ForwardingReason {
	NEXT_HOP_NOT_FOUND,
	HOST_NOT_FOUND_ON_SUBNET,
	FORWARDING_SUCCESS,
	ROUTER_RETURN_REACHED,
	NO_RETURN_ROUTE,
	FORWARDING_FAILURE_NO_RETURN_ROUTE,
	INTERFACE_ADMIN_DOWN,
	NEXT_HOP_NOT_IN_TOPOLOGY,
	TTL_EXPIRED,
	INTERFACE_NOT_CONNECTED,
	NO_ROUTE,
	FORWARDING_FAILURE_INTERFACE_ADMIN_DOWN,
	INVALID_ROUTE,
	UNSUPPORTED_NEIGHBOR_TYPE,
	ROUTER_INTERFACE_REACHED,
	REACHED_SAME_SUBNET,
	REACHED_HOST,
	RETURN_REACHED_HOST,
	NO_DEFAULT_GATEWAY,
	HOST_NOT_CONNECTED,
	DEFAULT_GATEWAY_NOT_ROUTER,
	CANNOT_FIND_ROUTER_FOR_GATEWAY,
	NEIGHBOR_ROUTER_NOT_FOUND
}